### ISSUE TITLE
Multi-cloud setup/solve/check scripts log more for Instruqt

### ISSUE THREAD

**Issue by thomashashi** [hashicorp/field-workshops-consul#189]
When there's an error detected by CircleCI running the track tests, we have to kinda guess when and where the logs are from `instruqt track logs`.

Each of these scripts should `echo $INSTRUQT_PARTICIPANT_ID` as well as the date/time the script started/ended. With that we can leverage 

```Usage:
  instruqt track logs [TRACK] [flags]

Examples:
To tail logs of a track, starting 10 minutes ago:

  $: instruqt track logs my-first-track --since 10m



Flags:
  -h, --help                    help for logs
      --participant-id string   The participant ID. When set, this will take precedence over track ID or slug
      --since string            The start datetime from which to return logs
```

to find the exact logs from Instruqt and not have to guess.

**Comment by omkensey** [comment]
We can do the first by logging in the test action (CircleCI/GitHub Actions) instead (we get an approximate idea from the CircleCI task start times but it would be nice not to have to do the math).  We won't see the output of the track scripts until we're already scrolling logs (so regarding the second part, we won't get participant ID from track scripts until after scanning track logs and seeing it prefixed there anyway).

What we really need is for Instruqt to report back to the CLI (and the CLI to output) the start time and participant ID, so it will be recorded in the test action output, which we put in as a request from our side some time ago.

**Comment by thomashashi** [comment]
Oh, good point. Do you have a link to that request we made to Instruqt? I want to not it here for posterity.
