### ISSUE TITLE
Intro to Consul Slide Deck Mismatch

### ISSUE THREAD

**Issue by dahr** [hashicorp/field-workshops-consul#241]
The Intro to Consul is split into three sections as per the [Confluence Page](https://hashicorp.atlassian.net/wiki/spaces/VE/pages/2364834447/WORKSHOP+CATALOG):

1. Consul Basics
2. Service Discovery
3. Service Mesh

The slide deck mirrors this.  However, after the "Service Discovery" section (Section 2), the Lab Exercise page reads, "Service Mesh with Consul Enterprise" even though this is not covered until the last section.  Furthermore, there is no lab exercise page for "Service Mesh" after covering the topic in the slides.

Need to:

1. Change the second Lab Exercise page to read, "Service Discovery with Consul Enterprise".
2. Add a final Lab Exercise page that reads, "Service Mesh with Consul Enterprise.

**Comment by thomashashi** [comment]
Handled in IL-892, closing here.
