### ISSUE TITLE
Insruqt lab- Consul High Availability

### ISSUE THREAD

**Issue by vincentramirez** [hashicorp/field-workshops-consul#33]
My leader was Consul0, I did a pkill consul on Consul0,
lost access to my Consul UI, but after the leader election and a leader was defined
the UI did not come back.  Even after several refreshes in the Instruqt browser refresh.
After restoring Consul from two node failures, the Consul UI does come back online.

It may just be more of a confusion for students than anything else.  Not sure if this is just buggy behavior for the Instruqt lab

**Comment by lanceplarsen** [comment]
This is  intended behavior for the lab. We've added the following note: `If your leader happens to be Consul0 you will temporarily lose access to the UI.`
