### ISSUE TITLE
Insruqt lab - Service Mesh with Consul typo

### ISSUE THREAD

**Issue by rejackson73** [hashicorp/field-workshops-consul#37]
https://instruqt.com/hashicorp/tracks/service-mesh-with-consul/challenges/sidecar-proxies/assignment

We've "played" instead of "placed"

![image](https://user-images.githubusercontent.com/28791872/65905029-c403fb80-e38d-11e9-8983-990d500eff0c.png)

**Comment by lanceplarsen** [comment]
fixed
