### ISSUE TITLE
service-mesh-with-consul needs to be more clear on which file and line are to be edited

### ISSUE THREAD

**Issue by scarolan** [hashicorp/field-workshops-consul#39]
In the lab “service-mesh-with-consul” -> enable -localhost-proxy-> assignment. It saids — Remember, our listener is configured on localhost, so we can just update our properties file to 127.0.0.1, and establish connectivity.

**Comment by OnionTing** [comment]
Please make note to say -- Update the Line 32 of wp-config.php file under "xxx" tab, change the IP address to be "127.0.0.1".
