### ISSUE TITLE
Instruqt Labs - Time out disrupts exercises

### ISSUE THREAD

**Issue by kaitlincarter-hc** [hashicorp/field-workshops-consul#65]
I found that if I navigate away from the instuqt labs they time out, causing me to start from the beginning. Since we can't increase the time out (per issue #15), I think we could inform users of how much time they have until the server is destroyed and/or unlock the exercises so you don't have to complete them in order.

**Comment by lanceplarsen** [comment]
Moving this to general Instruqt feedback
